### ISSUE TITLE
Does not parse minified jQuery 1.5.2

### ISSUE THREAD

**Issue by scottfrazer** [haileys/twostroke#1]
Nice job on the parser.  I did, however, try jQuery 1.5.2 minified and was not able to parse it, thought you might want to know!

http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js

**Comment by haileys** [comment]
Twostroke can now parse the bleeding edge jquery [core.js](https://github.com/jquery/jquery/blob/master/src/core.js). It can't parse the whole thing due to some precedence issues, but I'm working on fixing those up!

**Comment by haileys** [comment]
Parses unminified jQuery: https://github.com/charliesome/twostroke/commit/954055785ec703bd941f17ab4e82ef3d3aa12b8a

**Comment by haileys** [comment]
Twostroke is now able to parse jQuery 1.5.2 minified.
