### ISSUE TITLE
Assertion in test using Japanese Windows XP / Ruby Installer

### ISSUE THREAD

**Issue by fritzsche** [haileys/twostroke#5]
Hi Charlie,

after fix reported in issue #4 I can run the test suite but still have 2 assertions as shown below.
I understand that windows might not be in focus on this early stage of development but any ideas?

Thanks, Thomas

...................................
test/exceptions.js
    FAIL  finally still executes if catch throws an exception and the exception keeps bubbling up
      Assertion failed after 0 assertions: 
....................................................
test/semicolon_insertion.js
    FAIL  return is greedily semicolon inserted
      Assertion failed after 0 assertions: <undefined> !== <1>  
.............................................................................................Coverage report generated for test.rb  to D:/Rails/twostroke/coverage. 2621 / 2742 LOC (95.59%) covered.

**Comment by haileys** [comment]
I shouldn't say that those failures are _supposed_ to be happening, but I do know about them and it isn't any of your fault.

One's for an edge case with exceptions that I have to fix, the other is a reminder for me to implement semicolon insertion.

I'll leave this ticket open until I fix that

**Comment by haileys** [comment]
All tests are passing now!
