### ISSUE TITLE
Ruby 1.8.7

### ISSUE THREAD

**Issue by DAddYE** [haileys/twostroke#8]
Is there a possibility to backport it on 1.8.7?

I know that is in(complete) but seems to work well, so my guess is to use it in production where I need coffee and stylus :D

Thank you man!

**Comment by haileys** [comment]
I probably wouldn't consider Twostroke ready to run in production at the moment.

As for backporting it to 1.8, there's plenty of 1.9-isms scattered throughout the code - most significantly named regexp captures - that would be tricky to fix up for 1.8.

If you'd like to contribute a patch to add 1.8 support, I'd gladly accept it.
